package com.monibank.mainframe.customer;

import com.monibank.mainframe.customer.api.CreateCustomerRequest;
import com.monibank.mainframe.customer.api.CustomerResponse;
import com.monibank.mainframe.customer.api.GetCustomerRequest;
import com.monibank.mainframe.customer.mainframe.CustomerMainframeOperations;
import com.monibank.mainframe.customer.mainframe.CustomerRecordMapper;
import com.monibank.mainframe.customer.mainframe.CustomerRecordParser;
import com.monibank.mainframe.hercules.KicksMainframeOperationExecutor;
import com.monibank.mainframe.model.MainframeDataRecord;
import com.monibank.mainframe.model.MainframeResult;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
@RequiredArgsConstructor
public class CustomerService {

    private final CustomerRecordMapper customerRecordMapper;
    private final CustomerRecordParser customerRecordParser;
    private final KicksMainframeOperationExecutor
            kicksMainframeOperationExecutor;

    public CustomerResponse createCustomer(
            CreateCustomerRequest request
    ) {

        /*
         * ADDCUSG expects exactly 105 characters:
         * country, national ID, first name, last name,
         * date of birth and created-at timestamp.
         *
         * The request ID is generated by the KICKS executor
         * and carried separately in MBGWCA.
         *
         * The customer ID is generated by SEQFILE
         * on the mainframe.
         */
        String inputRecord =
                customerRecordMapper.toRecord(request);

        MainframeResult result =
                kicksMainframeOperationExecutor.execute(
                        CustomerMainframeOperations.ADD_CUSTOMER,
                        inputRecord
                );

        String createdCustomerId =
                result.header().entityId();

        validateCustomerId(
                createdCustomerId,
                CustomerMainframeOperations.ADD_CUSTOMER
        );

        return parseSingleCustomer(
                result,
                createdCustomerId,
                CustomerMainframeOperations.ADD_CUSTOMER
        );
    }

    public CustomerResponse getCustomer(
            GetCustomerRequest request
    ) {

        MainframeResult result =
                kicksMainframeOperationExecutor.execute(
                        CustomerMainframeOperations.GET_CUSTOMER,
                        request.customerId()
                );

        return parseSingleCustomer(
                result,
                request.customerId(),
                CustomerMainframeOperations.GET_CUSTOMER
        );
    }

    public CustomerResponse changeStatus(
            String customerId,
            String status
    ) {

        /*
         * CHGCUST expects exactly 14 characters:
         * customer ID X(13) + status X(1).
         *
         * Request ID is generated by the KICKS executor
         * and carried separately in MBGWCA.
         */
        String inputRecord =
                customerRecordMapper.toStatusUpdateRecord(
                        customerId,
                        status
                );

        MainframeResult result =
                kicksMainframeOperationExecutor.execute(
                        CustomerMainframeOperations.CHANGE_STATUS,
                        inputRecord
                );

        return parseSingleCustomer(
                result,
                customerId,
                CustomerMainframeOperations.CHANGE_STATUS
        );
    }

    public List<CustomerResponse> getCustomers() {

        MainframeResult result =
                kicksMainframeOperationExecutor.execute(
                        CustomerMainframeOperations.LIST_CUSTOMERS,
                        ""
                );

        return parseCustomers(result);
    }

    private List<CustomerResponse> parseCustomers(
            MainframeResult result
    ) {

        return result.data()
                .stream()
                .filter(this::isCustomer)
                .map(MainframeDataRecord::payload)
                .map(customerRecordParser::parse)
                .toList();
    }

    private CustomerResponse parseSingleCustomer(
            MainframeResult result,
            String expectedCustomerId,
            String operation
    ) {

        List<CustomerResponse> customers =
                parseCustomers(result);

        if (customers.size() != 1) {
            throw new IllegalStateException(
                    operation
                            + " returned "
                            + customers.size()
                            + " CUSTOMER records; expected 1"
            );
        }

        CustomerResponse customer =
                customers.getFirst();

        if (!expectedCustomerId.equals(
                customer.customerId()
        )) {
            throw new IllegalStateException(
                    operation
                            + " returned customer "
                            + customer.customerId()
                            + ", expected "
                            + expectedCustomerId
            );
        }

        return customer;
    }

    private boolean isCustomer(
            MainframeDataRecord record
    ) {

        return "CUSTOMER".equals(
                record.entityType()
        );
    }

    private void validateCustomerId(
            String customerId,
            String operation
    ) {

        if (customerId == null
                || !customerId.matches("C\\d{12}")) {
            throw new IllegalStateException(
                    operation
                            + " returned invalid customer ID: "
                            + customerId
            );
        }
    }
}