package com.monibank.mainframe.customer.mainframe;

import com.monibank.mainframe.customer.api.CreateCustomerRequest;
import com.monibank.mainframe.mapping.MainframeRecordMapper;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Objects;

@Component
public class CustomerRecordMapper
        implements MainframeRecordMapper<CreateCustomerRequest> {

    private static final DateTimeFormatter DATE_FORMAT =
            DateTimeFormatter.ofPattern("yyyyMMdd");

    private static final DateTimeFormatter CREATED_AT_FORMAT =
            DateTimeFormatter.ofPattern("yyyyMMddHHmmss");

    @Override
    public String toRecord(
            CreateCustomerRequest request
    ) {

        Objects.requireNonNull(
                request,
                "Create customer request cannot be null."
        );

        String dateOfBirth =
                request.dateOfBirth()
                        .format(DATE_FORMAT);

        String createdAt =
                LocalDateTime.now()
                        .format(CREATED_AT_FORMAT);

        String record =
                fixed(request.countryCode(), 2)
                        + fixed(request.nationalId(), 11)
                        + fixed(request.firstName(), 30)
                        + fixed(request.lastName(), 40)
                        + fixed(dateOfBirth, 8)
                        + fixed(createdAt, 14);

        requireLength(
                record,
                105,
                "Customer data"
        );

        return record;
    }

    /*
     * CHGCUST receives:
     * customerId X(13) + status X(1) = 14 characters.
     *
     * Request ID is generated by KicksMainframeOperationExecutor
     * and transported separately in MBGWCA.
     */
    public String toStatusUpdateRecord(
            String customerId,
            String status
    ) {

        validateCustomerId(customerId);

        if (!"A".equals(status)
                && !"I".equals(status)) {
            throw new IllegalArgumentException(
                    "Status must be A or I."
            );
        }

        String record =
                customerId + status;

        requireLength(
                record,
                14,
                "Customer status update record"
        );

        return record;
    }

    private void validateCustomerId(
            String customerId
    ) {

        if (customerId == null
                || !customerId.matches("C\\d{12}")) {
            throw new IllegalArgumentException(
                    "Customer ID must match C followed by 12 digits."
            );
        }
    }

    private String fixed(
            String value,
            int length
    ) {

        String safeValue =
                value == null
                        ? ""
                        : value;

        if (safeValue.length() > length) {
            throw new IllegalArgumentException(
                    "Value exceeds mainframe field length "
                            + length
                            + ": "
                            + safeValue
            );
        }

        if (safeValue.chars().anyMatch(
                Character::isISOControl
        )) {
            throw new IllegalArgumentException(
                    "Mainframe field contains a control character."
            );
        }

        return String.format(
                "%-" + length + "s",
                safeValue
        );
    }

    private void requireLength(
            String record,
            int expectedLength,
            String description
    ) {

        if (record.length() != expectedLength) {
            throw new IllegalStateException(
                    description
                            + " must have length "
                            + expectedLength
                            + ", got "
                            + record.length()
            );
        }
    }
}